### ISSUE TITLE
Have an option to disable creating log group/metrics

### ISSUE THREAD

**Issue by eduardomourar** [eduardomourar/cloudformation-cli-typescript-plugin#19]
As discussed with Olaf, we should have an option to disable pushing data to CloudWatch, and possibly avoid creating the resources (metrics, log groups, log streams) themselves.

**Comment by OlafConijn** [comment]
registering the type of cli (or soon: org-formation) without loggingConfiguration seems to have the desired effect. for me can be closed. thanks!
